<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The Most Powerful Crypto Trading Tool</name>
   <tag></tag>
   <elementGuidId>6eb278cd-472f-4ebe-aa99-da6cb43725a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Most Powerful Crypto Trading Tool:All the Signals and Tools You Need To Become a Profitable TraderMonthly$299 /month 1 month membershipNo Setup FeeCancel AnytimeGet StartedCrypto Payment:*Crypto payment is only available for Quarterly and Yearly SubcriptionsSave 33% /mQuarterlyMost Popular$200  /monthSave $298 per quarterBilled QuarterlyNo Setup FeeCancel AnytimeGet StartedCrypto Payment:Yearly $167 /monthSave up to $1589 per yearBilled YearlyNo Setup FeeCancel AnytimeGet StartedCrypto Payment:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sc-gGCDDS jwwXMs&quot;]/div[@class=&quot;sc-Galmp iQwxOv&quot;]/div[@class=&quot;sc-ZOtfp eDUWNw&quot;]/div[@class=&quot;default-container container&quot;]/div[@class=&quot;center row&quot;]/div[@class=&quot;custom-card card&quot;]/div[@class=&quot;card-body&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
